### ISSUE TITLE
Error in list_programs() function in QBMS

### ISSUE THREAD

**Issue by awkena** [icarda-git/QBMS#14]
I get this error whenever I try to access the list of programs from BMS. 
> QBMS::list_programs() # data frame
Error in stop(http_error(resp)) : Forbidden (HTTP 403)

**Comment by khaled-alshamaa** [comment]
Please take note of the BMS permissions required for using BrAPI services for BMS v25 and onwards:
https://ibplatform.atlassian.net/wiki/spaces/BMS/pages/2870968321/v25+BMS+permissions+required+for+using+BrAPI+services

**Comment by khaled-alshamaa** [comment]
Dear @awkena, 
We will close this issue by the end of this week if we get no feedback or confirmation from your side.

**Comment by khaled-alshamaa** [comment]
Please feel free to reopen this ticket if you believe that your issue isn't appropriately resolved!
