### ISSUE TITLE
Error in brapi_get_call() -- namespace issue?

### ISSUE THREAD

**Issue by jmh579** [icarda-git/QBMS#15]
I'm using QBMS v0.9.1. Following the Breedbase vignette, I get the following error after `list_crops()`:

`Error: 'synchronise' is not an exported object from 'namespace:async'`

This happens with other QBMS functions too, not just `list_crops()` -- `async::synchronise()` is called in the `brapi_get_call()` function in qbms.R (lines 444 and 450). From what I can tell, `synchronise` is not a function exported by the CRAN package [`async`](https://github.com/crowding/async/), which is why it's throwing an error. 

This is my first time trying out QBMS, so entirely possible I'm missing something. Thanks in advance for your help!

**Comment by khaled-alshamaa** [comment]
Most probably it is regarding the [async](https://github.com/gaborcsardi/async) R package that our QBMS uses internally ([more details here](https://icarda-git.github.io/QBMS/#boosting-big-queries-performance)). It is different from the other ***async*** package published on the [CRAN repository](https://cran.r-project.org/package=async).

To fix this issue, uninstall your async package and then install the one suggested by QBMS from the GitHub repository using the following `remotes` package functionality:
```r
remotes::install_github("r-lib/async")
```

That should resolve the problem that you had.

**Comment by jmh579** [comment]
Thanks, @khaled-alshamaa! 

I've followed your instructions and should now have your suggested async package installed, but I am now getting a different error:

```
Error in async::async({ : 
  unused arguments (local = FALSE, split_pipes = TRUE, compileLevel = 0, debugR = FALSE, debugInternal = FALSE, trace = FALSE)
```

Any ideas for what might be causing this?

**Comment by khaled-alshamaa** [comment]
Dear @jmh579,

This is exactly what I am trying to say! You have installed the wrong async package (look to the function parameters in your error message): https://crowding.github.io/async/reference/async.html

Therefore, please try the following code snippet to fix this issue:
```r
remove.packages("async")
if("package:async" %in% search()) detach("package:async", unload = TRUE)
remotes::install_github("r-lib/async")
```
Are you using MacOS?

**Comment by khaled-alshamaa** [comment]
@AparicioJohan, I recall you dealt with a similar issue in the past. Could you please provide @jmh579 with any best practices or lessons learned? Thanks!

**Comment by AparicioJohan** [comment]
Hi @khaled-alshamaa and @jmh579,

A couple of colleagues mentioned that they've encountered this issue as well (on mac). Oddly enough, we found that simply restarting the PC and uninstalling and reinstalling the packages resolved the problem.

**Comment by jmh579** [comment]
That worked for me! I guess I need to get in the habit of restarting my computer more often. 

Thank you, @AparicioJohan and @khaled-alshamaa!!

**Comment by tyrwh** [comment]
@AparicioJohan @khaled-alshamaa I was getting the same error as @jmh579 but had to follow a specific install order to get the library to function. Commenting here in case others encounter this issue in the future--

I had the other version of `async` installed previously, presumably as a dependency for some other library.

The steps that worked for me were to uninstall `QBMS` and `async`, restart, install `async` via `remotes::install_github("r-lib/async")`, then install `QBMS` via `remotes::install_github("r-lib/async")`

Here are the install steps that did _not_ work for me:
1. Uninstall `async`, reinstall via `remotes::install_github("r-lib/async")`
2. Restart, uninstall `async`, reinstall `async` with `remotes`
3. Restart, uninstall `QBMS` and `async`, reinstall `QBMS` from CRAN and `async` via `remotes`
4. Restart, uninstall `QBMS` and `async`, reinstall `QBMS` via `remotes` and then `async` via `remotes`
5. Uninstall `QBMS` and `async`, restart, reinstall `QBMS` via `remotes` and then `async` via `remotes`

On Mac, R 4.2.2
