### ISSUE TITLE
Error in list_crops()

### ISSUE THREAD

**Issue by awkena** [icarda-git/QBMS#17]
I get this error in R whenever I try importing trials from BMS. The error is related to the async package. It appears the author of the async package made recent changes in the async function, triggering the error below. 

crops <- QBMS::list_crops() 

Error in async::async({ : 
  unused arguments (local = FALSE, split_pipes = TRUE, compileLevel = 0, debugR = FALSE, debugInternal = FALSE, trace = FALSE)

**Comment by khaled-alshamaa** [comment]
You have a different [async](https://cran.r-project.org/package=async) R package from CRAN repo on your system! You can uninstall it, and reinstall the other [async](https://github.com/gaborcsardi/async) package that QBMS use:
```r
remove.packages("async")
if("package:async" %in% search()) detach("package:async", unload = TRUE)

remotes::install_github("r-lib/async")
```
For more details, please refer to this [GitHub issue](https://github.com/icarda-git/QBMS/issues/15)
