### ISSUE TITLE
Error when listing programs

### ISSUE THREAD

**Issue by chris263** [icarda-git/QBMS#18]
> set_qbms_config("https://cassavabase.org/brapi/v2", no_auth = TRUE, engine = "breedbase")
> list_crops()
[1] "Cassava"
> set_crop("Cassava")
> list_programs() ## The issue happens here
Error: lexical error: invalid char in json text.
                                       <?xml version="1.0" encoding="U
                     (right here) ------^

**Comment by khaled-alshamaa** [comment]
Dear @chris263, thanks for reporting this issue :-)
You can avoid it by not calling `set_crop()` function if you connect to a BreedBase system ([check this example](https://icarda-git.github.io/QBMS/articles/breedbase_example.html#example)).
We will resolve this issue in the next version of QBMS even if you call the `set_crop()` function ;-)
